# Window setup of GUI - ../budget_app/views.py
APP_NAME = "Presupuesto"
WIDTH = 800
HEIGHT = 500

# Paddings
LABEL_PAD_X = 10
LABEL_PAD_Y = 5

BUTTON_PAD_X = 20
BUTTON_PAD_Y = 10

SHORT_PAD_X_LEFT = 10
SHORT_PAD_X_RIGHT = 10

SHORT_PAD_Y_TOP = 10
SHORT_PAD_Y_BOTTOM = 10
LARGE_PAD_Y_TOP = 40
LARGE_PAD_Y_BOTTOM = 40

# Orientation
LABEL_ORIENTATION = "e"
ENTRY_ORIENTATION = "ew"
COMBO_ORIENTATION = "ew"
BUTTON_ORIENTATION = "nsew"
